# site settings

title: Nik Dot Codes
description: The semi-coherent ramblings of a database jockey, runner, & TTRPG enthusiast.
taglong: Data Architect by day, a GM that runs by night
tagshort: and tries other things
url: https://www.nik.codes
baseurl: ""
permalink: /blog/:categories/:year/:month/:title.html

show_drafts: false

# author settings

author: 
  name: Nik
  email: hi@nik.codes
photo: /assets/jpg/header.png

# social media links

social:
  github: nikdotcodes
  linkedin: nikdotcodes
  strava: nikdotcodes
  bluesky: nik.codes

# flags to turn things off and on insite

flags:
  ttrpg: true

# blog settings
imagelib: /assets/jps/blog/

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 3
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
